### PR TITLE
Fix library integration when user use special paths

### PR DESCRIPTION
**Pull request by antonsoroko**
If user decided to make Kodi library portable by using `special://` paths when adding library sources, then we need to resolve those paths in elementum.
This change will not affect users with "normal" paths (and there should not be any noticeable performance penalty).

Should fix https://github.com/elgatito/plugin.video.elementum/issues/949

### CODE REVIEW

**Comment by susobaco** [comment]
@antonsoroko Sorry, I'm not very used to doing this. The platform is amd64 so it will be "plugin.video.elementum-0.1.98.linux_x64.zip".   

I can't find the library "library.go" to apply the patch, can it be that it has to be compiled?

Thanks and apologies.

**Comment by antonsoroko** [comment]
@susobaco yes, it must be compiled. that's why i asked you for platform. i put a link in https://github.com/elgatito/plugin.video.elementum/issues/949  - let's continue our conversation there.

**Comment by antonsoroko** [comment]
@elgatito может будет время замержить?) спасибо.

**Comment by antonsoroko** [comment]
оказывается я забыл обновить getMoviePathsByTMDB, теперь вроде всё ок.

**Pull request merged**
