### PR TITLE
AllowKodiChangeArtworksNonLibrary

### PR DESCRIPTION
**Pull request by antonsoroko**
for https://github.com/elgatito/plugin.video.elementum/issues/795
depends on https://github.com/elgatito/plugin.video.elementum/pull/790

### CODE REVIEW

**Comment by elgatito** [comment]
@antonsoroko Why this is needed? It will not allow to change artwork for something that is not in the library.

**Comment by antonsoroko** [comment]
@elgatito 
it will if user will enable it.

but looks like that some skins uses some addons that fail when they see fake lib id.

https://github.com/elgatito/plugin.video.elementum/issues/795#issuecomment-864882486

**Comment by antonsoroko** [comment]
log file example from user 
https://github.com/elgatito/plugin.video.elementum/issues/795#issuecomment-865012485

**Comment by antonsoroko** [comment]
close in favor of https://github.com/elgatito/elementum/pull/74

**Pull request closed without merging**
