### PR TITLE
Add params to /info endpoint + gzip

### PR DESCRIPTION
**Pull request by antonsoroko**
for https://github.com/elgatito/plugin.video.elementum/pull/740

example:
`http://ip:65220/info?torrentid=9d21b9bb34036bdaa4745fa0782e63636fc467b9&showtrackers=false`

old endpoint `http://ip:65220/info` has no changes.

### CODE REVIEW

**Comment by antonsoroko** [comment]
alternatively we can use bytes.Buffer if it makes more sense:

```diff
diff --git a/bittorrent/service.go b/bittorrent/service.go
index 80702e5..02a1b29 100644
--- a/bittorrent/service.go
+++ b/bittorrent/service.go
@@ -1624,8 +1624,10 @@ func (s *Service) InfoWeb(ctx *gin.Context) {
 
 	defer perf.ScopeTimer()()
 
+	var b bytes.Buffer
+
 	ctx.Writer.Header().Set("Access-Control-Allow-Origin", "*")
-	ctx.Header("Content-Type", "text/plain; charset=utf-8")
+	//ctx.Header("Content-Type", "text/plain; charset=utf-8")
 
 	torrentID := ctx.Query("torrentid")
 
@@ -1638,7 +1640,8 @@ func (s *Service) InfoWeb(ctx *gin.Context) {
 	if torrentID != "" {
 		t := s.GetTorrentByHash(torrentID)
 		if t != nil && t.th != nil {
-			t.TorrentInfo(ctx.Writer, showTrackers)
+			//t.TorrentInfo(ctx.Writer, showTrackers)
+			t.TorrentInfo(&b, showTrackers)
 		}
 	} else {
 		for _, t := range s.q.All() {
@@ -1646,11 +1649,14 @@ func (s *Service) InfoWeb(ctx *gin.Context) {
 				continue
 			}
 
-			t.TorrentInfo(ctx.Writer, showTrackers)
+			//t.TorrentInfo(ctx.Writer, showTrackers)
+			t.TorrentInfo(&b, showTrackers)
 
-			fmt.Fprint(ctx.Writer, "\n\n")
+			//fmt.Fprint(ctx.Writer, "\n\n")
+			fmt.Fprint(&b, "\n\n")
 		}
 	}
+	ctx.Data(200, "text/plain; charset=utf-8", b.Bytes())
 }
 
 // AttachPlayer adds Player instance to service
```

**Comment by elgatito** [comment]
@antonsoroko The idea of gzip is to save time on transmitting data over network. Elementum is run on a localhost, and requested from localhost. That is why gzip is not used. It will make cpu usage to gzip/unzip the data.

**Comment by elgatito** [comment]
@antonsoroko Please, take a look at the latest commit.

I have set global headers for CORS. Moved /info to gin handling.
In perfect, all other handlers from main.go should be moved there (except for /files).

**Comment by antonsoroko** [comment]
@elgatito 
I wanted to use gzip only for web UI endpoints (so it will be not local) but looks like that library does not support this.

yeah, your implementation looks better :-) thanks.

**Pull request closed without merging**
