### PR TITLE
[Feature] add proxy to tmdb MakeRequest

### PR DESCRIPTION
**Pull request by vanadium23**
TMDB start to ban requests in some countries.

### CODE REVIEW

**Comment by antonsoroko** [comment]
btw, are you sure that it bans requests and not built-in api key?

some ideas for testing it, if you are interested:
https://github.com/elgatito/plugin.video.elementum/issues/874#issuecomment-1094292713

**Comment by vanadium23** [comment]
Pretty sure, that this is a ban for country code from Cloudfront.

image

**Comment by vanadium23** [comment]
Do I need something to rewrite or close PR?

**Comment by antonsoroko** [comment]
only elgatito can merge PR.

**Comment by betapl3b** [comment]
@vanadium23 your fix is working fine. I have built and installed it. Now proxy from elementum is used for tmdb requests. Thanks a lot!

**Comment by betapl3b** [comment]
BTW images' downloads seem to fail. As they are performed using other module.
ERROR <general>: CCurlFile::Stat - Failed: Couldn't connect to server(7) for https://image.tmdb.org/t/p/w1280/6z8Hz5TJL5Txji9rrcq3iuy01iC.jpg

**Pull request merged**
