### PR TITLE
fix show search file regex

### PR DESCRIPTION
**Pull request by vasilky3**
false positive match on absolute 00112 episode with 0*{s}0*{ep} regex

### CODE REVIEW

**Comment by vasilky3** [comment]
@elgatito, i was thinking my description is unclear. So here is more examples.

lets say i want to find an episode by absolute number 8 in torrent file containing 1-200 ep
I will receive `season = 1 ep = 8`

now using `\W0*(1)0*(8)`
i will find ep 018 and 108  in https://github.com/vasilky3/elementum/blob/master/bittorrent/player.go#L1515
and will select episode manually in GUI.

while it spoused to be 008 using `singleEpisodeMatchRegex` here https://github.com/vasilky3/elementum/blob/master/bittorrent/player.go#L1527

More over in some cases `MatchEpisodeFilename` returns one wrong number and starts wrong ep. And where is no way to workaround from GUI.
Example:
lets say i want to find an episode by absolute number 12 in torrent file containing 1-200 ep
I will receive `season = 1 ep = 12`
now using `\W0*(1)0*(12)`
I got ep 112. And elementum will start it, while i was looking for ep 012.

**Comment by elgatito** [comment]
@vasilky3 I still have a feeling that you fix one bug by introducing another one...

There are valid cases when we should have a season 1 torrent with filenames like `{season}0{episode}.*` for season `{season}` episode `{episode}`. And that is not with absolute numbering. 

And you change requires to have `\D{1,5}` between season and episode number (btw, why up to 5 non-digit characters?).

This is tricky, because you never know if numbering in the torrent is by absolute numbers or season based.

**Comment by vasilky3** [comment]
@elgatito, your example:
`{season}0{episode}` - this type of naming seems strange for me. I suppose season and episode should be separated by any non digit character, otherwise it's one digit. Regarding the numbering (absolute or not).
Magic number 5 - is stupid. But I thought about something like `] - [` in the longest scenario. 

If `{season}0{episode}` is legit for naming. 
I can explicitly call specific regex for absolute numbering. This way regex will be separated.

**Comment by vasilky3** [comment]
One more thing about `{s}0*{ep}` regex. 
It seems to be flaky even in normal scenario. 
Let's say I have a torrent containing all the seasons with such a strange nummering
112 - is it s11e2 or s1ep12
102 - is it s1e02 or s10ep2
For this type of naming manual file select is ok

**Comment by elgatito** [comment]
@vasilky3 I think at most we will loose auto selection for specific pattern. Let's see if that needs to be reverted. Will merge it and watch.

Thanks

**Pull request merged**
